#!/bin/bash

set -e
set -u

year="${1}"
day="${2}"

# local
dest="$year/$day"

# remote
aoc="https://adventofcode.com"
challenge="$aoc/$year/day/$day"

test -d $dest || mkdir -p $dest

echo "\
# $challenge

import os


def resolve(name=\"input.txt\"):
    return os.path.join(os.path.dirname(__file__), name)


def solve(datafile=\"input.txt\"):
    pass


def test():
    assert solve(\"test.txt\") is None


test()
print(solve())
" > $dest/code.py

curl -s -H "Cookie: session=${AOC_SESSION_ID}" $challenge/input > $dest/input.txt

touch $dest/test.txt