#!/bin/bash

set -e
set -u


function token {
    t=${2}

    echo $t > .token
}


function check_token {
    if [ ! -f .token ]; then
        echo "No token found. Please run 'aoc token <token>'"
        exit 1
    fi
}


function pull {
    year="${2}"
    day="${3}"

    # Check that we have a token
    check_token

    token=$(cat .token)

    # local
    dest="$year/$day"

    # remote
    aoc="https://adventofcode.com"
    challenge="$aoc/$year/day/$day"

    test -d $dest || mkdir -p $dest

    echo "\
# $challenge

from aoctk.input import get_lines


def solve(data=\"input.txt\"):
    pass


def test():
    assert solve(\"test.txt\") is None


def part_one():
    pass


def part_two():
    pass\
" > $dest/code.py

    curl -s -H "Cookie: session=${token}" $challenge/input > $dest/input.txt

    touch $dest/test.txt
}


function run {
    year="${2}"
    day="${3}"

    source .venv/bin/activate
    
    PYTHONPATH=$year/$day python -c "import code; code.test(); print('Test OK'); print('Part 1:', code.part_one()); print('Part 2:', code.part_two())"
    
    deactivate
}


function main {
    cmd="$1"

    case $cmd in
        token)
            token $@
            ;;
        pull)
            pull $@
            ;;
        run)
            run $@
            ;;
        *)
            echo "Unknown command: $cmd"
            ;;
    esac
}


main $@
